services:
  - type: web
    name: hrms-lite-api
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port 8000
    root: .
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
        sync: false
      - key: CORS_ORIGINS
        value: https://your-vercel-domain.vercel.app
        scope: build,runtime
      - key: ALLOW_CORS_ALL
        value: "false"
        scope: build,runtime
      - key: DEBUG
        value: "false"
        scope: build,runtime

  - type: pserv
    name: hrms-lite-db
    plan: free
    ipAllowList: []
    postgresMajorVersion: 15
