services:
  - type: web
    name: hrms-lite-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000
    root: .
    pythonVersion: 3.9
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
        sync: false
      - key: CORS_ORIGINS
        value: https://hrms-lite.vercel.app
        scope: build,runtime
      - key: ALLOW_CORS_ALL
        value: "false"
        scope: build,runtime
      - key: DEBUG
        value: "false"
        scope: build,runtime

  - type: pserv
    name: hrms-lite-db
    plan: free
    ipAllowList: []
    postgresMajorVersion: 15
