services:
  - type: web
    name: hrms-lite-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    root: backend
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
        sync: false
      - key: CORS_ORIGINS
        value: https://your-frontend-url.vercel.app
        scope: build,runtime

  - type: pserv
    name: hrms-lite-db
    plan: free
    ipAllowList: []
    postgresMajorVersion: 15
